export const DIRECT_IMAGE_PROMPT = (style: string, instructions: string): string => {
  return [
    `Regenerate this floor plan into a professional ${style || "CAD Blueprint"} style.`,
    'This is a DIRECT IMAGE-TO-IMAGE TRANSFORMATION. Follow every specification below exactly.',
    '',
    '━━━ GEOMETRY PRESERVATION ━━━',
    'Strictly preserve the exact geometry of the uploaded floor plan:',
    '- room positions, wall layout, doors, windows must stay identical',
    '- do NOT move, resize, rotate, or reinterpret any structural element',
    '- the output must be a direct restyling, not a redesign',
    '',
    '━━━ LABEL HANDLING ━━━',
    '- IF text, room names, labels, or annotations exist in the input → preserve them exactly as-is',
    '- IF NO text or labels exist → do NOT invent, guess, or add any room names whatsoever',
    '- Never place made-up text like "Bedroom", "Kitchen", "Living Room" where none existed',
    '',
    '━━━ EXACT COLOR PALETTE (match this precisely) ━━━',
    '- Background: pure white (#FFFFFF)',
    '- Wall fill: soft light blue-gray (#B0C4DE / 176,196,222)',
    '- Wall borders / outlines: dark navy blue (#1A237E or #2C3E7B) — thin, crisp strokes',
    '- Doors: dark blue thick solid lines with curved dotted swing arcs',
    '- Windows: dark blue parallel thin lines on light blue wall fill',
    '- Labels / text: dark blue or black sans-serif font, clean and readable',
    '- Dimension lines: thin dark gray/blue with arrow ticks',
    '- Never use pure black (#000000) fills or thick black borders',
    '- Never use gray or dark fills inside rooms — only the light blue-gray wall fill',
    '',
    '━━━ LINE QUALITY ━━━',
    '- All lines must be clean, crisp, anti-aliased, CAD-quality strokes',
    '- Wall outlines: 2-3px weight, dark navy blue',
    '- Internal dividers / thin walls: 1-1.5px weight',
    '- Door arcs: dashed/dotted thin lines',
    '- Dimension lines: 0.5-1px weight with arrowheads',
    '',
    '━━━ OVERALL AESTHETIC ━━━',
    '- Pure 2D orthographic top-down view (no perspective, no 3D)',
    '- Clean pharmaceutical / architectural CAD schematic appearance',
    '- High contrast between white background and light blue walls with dark borders',
    '- No shadows, no gradients, no 3D effects',
    '- Professional-grade technical drafting appearance',
    instructions ? `\n\n━━━ ADDITIONAL INSTRUCTIONS ━━━\n${instructions}` : '',
  ].join('\n');
};
